/**
 * Versioned wire contract between the Chrome helper and /api/capture/v1/*.
 * Every request body is validated with these schemas at the boundary; unknown keys are rejected.
 */
import { z } from 'zod'
import {
  CAPTURE_LIMITS,
  CAPTURE_ROLES,
  CaptureModeSchema,
  CapturePageStateSchema,
  CaptureProblemStateSchema,
  CaptureProviderSchema,
  CaptureStateSchema,
} from './constants.ts'
import { CAPTURE_MESSAGE_KEY_RE } from './text.ts'
import { CAPTURE_UUID_RE, captureParseConversationUrl } from './urls.ts'

const uuid = z.string().regex(CAPTURE_UUID_RE, 'expected a UUID')
const count = z.number().int().min(0).max(1_000_000)
const isoInstant = z.iso.datetime({ offset: true })
const extensionVersion = z.string().regex(/^\d{1,5}(\.\d{1,5}){0,3}$/, 'expected a version like 0.1.0')

export const CaptureMessageSchema = z.strictObject({
  key: z.string().regex(CAPTURE_MESSAGE_KEY_RE).optional(),
  role: z.enum(CAPTURE_ROLES),
  text: z.string().max(CAPTURE_LIMITS.maxMessageChars),
  /** Position hint from the page (ChatGPT turn number, Claude row index). Ordering only. */
  orderHint: z.number().finite().min(-1e9).max(1e9).optional(),
  isStreaming: z.boolean().optional(),
})
export type CaptureMessage = z.infer<typeof CaptureMessageSchema>

export const CaptureCoverageSchema = z.strictObject({
  mode: CaptureModeSchema,
  /** True only if the helper actually saw the conversation's first message. */
  observedFirstMessage: z.boolean(),
  /** True only if the latest observation was at the end of the thread. */
  observedLastMessage: z.boolean(),
  /** Messages mounted in the page at the latest observation. */
  renderedCount: count,
  /** Messages collected while the page was open (virtualised threads mount a window at a time). */
  accumulatedCount: count,
  streamingInProgress: z.boolean(),
  pageState: CapturePageStateSchema,
  /** Messages the helper collected but left out of this snapshot (size limits, chunking). */
  omittedCount: count.optional(),
})
export type CaptureCoverage = z.infer<typeof CaptureCoverageSchema>

export const CaptureSnapshotSchema = z
  .strictObject({
    schemaVersion: z.literal(1),
    /** Generated by the helper; retries of the same upload reuse it. */
    snapshotId: uuid,
    provider: CaptureProviderSchema,
    conversation: z.strictObject({
      externalId: uuid,
      url: z.string().max(CAPTURE_LIMITS.maxUrlChars),
      title: z.string().max(CAPTURE_LIMITS.maxTitleChars).optional(),
    }),
    messages: z.array(CaptureMessageSchema).max(CAPTURE_LIMITS.maxMessages),
    capturedAt: isoInstant,
    coverage: CaptureCoverageSchema,
    extensionVersion,
  })
  .superRefine((snapshot, ctx) => {
    const ref = captureParseConversationUrl(snapshot.conversation.url)
    if (!ref || ref.provider !== snapshot.provider) {
      ctx.addIssue({ code: 'custom', path: ['conversation', 'url'], message: 'url_not_allowed' })
    } else if (ref.externalId !== snapshot.conversation.externalId.toLowerCase()) {
      ctx.addIssue({
        code: 'custom',
        path: ['conversation', 'externalId'],
        message: 'external_id_mismatch',
      })
    }
    const seen = new Set<string>()
    snapshot.messages.forEach((m, i) => {
      if (m.key === undefined) return
      if (seen.has(m.key)) {
        ctx.addIssue({ code: 'custom', path: ['messages', i, 'key'], message: 'duplicate_key' })
      }
      seen.add(m.key)
    })
  })
export type CaptureSnapshot = z.infer<typeof CaptureSnapshotSchema>

/** POST /api/capture/v1/status: the helper saw a problem on a selected conversation's page. */
export const CaptureStatusReportSchema = z.strictObject({
  schemaVersion: z.literal(1),
  provider: CaptureProviderSchema,
  externalId: uuid,
  state: CaptureProblemStateSchema,
  mode: CaptureModeSchema,
  observedAt: isoInstant,
  extensionVersion,
})
export type CaptureStatusReport = z.infer<typeof CaptureStatusReportSchema>

const deviceName = z
  .string()
  .trim()
  .min(1)
  .max(CAPTURE_LIMITS.maxDeviceNameChars)
  // Printable text only: no control characters or line breaks.
  .regex(/^[^\p{Cc}\p{Cf}\p{Zl}\p{Zp}]+$/u, 'invalid characters')

/** POST /api/capture/v1/pair */
export const CapturePairRequestSchema = z.strictObject({
  code: z.string().min(1).max(32),
  deviceName,
})
export type CapturePairRequest = z.infer<typeof CapturePairRequestSchema>

// ---------------------------------------------------------------------------
// Responses (validated by the helper before it trusts them)
// ---------------------------------------------------------------------------

export const CapturePairResponseSchema = z.strictObject({
  token: z.string().regex(/^phc_[A-Za-z0-9_-]{43}$/),
  dashboardOrigin: z.url(),
  deviceId: uuid,
})
export type CapturePairResponse = z.infer<typeof CapturePairResponseSchema>

export const CaptureSelectionItemSchema = z.strictObject({
  id: uuid,
  provider: CaptureProviderSchema,
  externalId: uuid,
  url: z.string().max(CAPTURE_LIMITS.maxUrlChars),
  captureState: CaptureStateSchema,
})
export type CaptureSelectionItem = z.infer<typeof CaptureSelectionItemSchema>

export const CaptureSelectionResponseSchema = z.strictObject({
  conversations: z.array(CaptureSelectionItemSchema).max(10_000),
  syncedAt: isoInstant,
})
export type CaptureSelectionResponse = z.infer<typeof CaptureSelectionResponseSchema>

export const CaptureSnapshotResponseSchema = z.strictObject({
  outcome: z.enum(['applied', 'ignored_partial', 'rejected']),
  newMessages: count,
  newVersions: count,
  captureState: CaptureStateSchema,
  duplicate: z.boolean(),
})
export type CaptureSnapshotResponse = z.infer<typeof CaptureSnapshotResponseSchema>

export const CaptureStatusResponseSchema = z.strictObject({ captureState: CaptureStateSchema })
export type CaptureStatusResponse = z.infer<typeof CaptureStatusResponseSchema>

/** Error bodies never echo request content: an error code plus schema paths at most. */
export const CaptureErrorResponseSchema = z.object({
  error: z.string(),
  captureState: CaptureStateSchema.optional(),
  issues: z.array(z.object({ path: z.string(), code: z.string() })).optional(),
})
export type CaptureErrorResponse = z.infer<typeof CaptureErrorResponseSchema>

/** Paths and codes of validation issues — never messages or received values. */
export function captureIssueSummary(error: z.ZodError, max = 20): { path: string; code: string }[] {
  return error.issues.slice(0, max).map((issue) => ({
    path: issue.path.map(String).join('.'),
    code: issue.code === 'custom' ? String(issue.message) : issue.code,
  }))
}
